version: "3"
services:
  frontend:
    build:
        context: frontend
        dockerfile: Dockerfile
    container_name: odyssey-frontend
    volumes:
        - ./frontend:/app
        - /app/node_modules
        - /app/.next
    extra_hosts:
        - localhost:127.0.0.1
    ports:
        - 3000:3000
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
    container_name: odyssey-backend
    volumes:
      - ./backend:/app
    ports:
        - 8000:8000