# Generated by Django 3.2.16 on 2022-12-01 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('issue', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mentorName', models.CharField(blank=True, max_length=50, null=True)),
                ('mentorId', models.CharField(blank=True, max_length=32, null=True)),
                ('assigneeName', models.CharField(blank=True, max_length=50, null=True)),
                ('assigneeId', models.CharField(blank=True, max_length=32, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('issueName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Issue',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardModel',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Leaderboard',
            },
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('enrollmentNo', models.CharField(max_length=8)),
                ('contactNo', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assignedIssue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odyssey.issuemodel')),
                ('completedIssues', models.ManyToManyField(blank=True, related_name='completedIssues', to='odyssey.IssueModel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
            },
        ),
    ]
