# Generated by Django 4.1.2 on 2022-11-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='issueDifficulty',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default='Easy', max_length=10),
        ),
    ]
