# Generated by Django 4.1.2 on 2022-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0002_issuemodel_issuedifficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='issueDifficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
